#!/bin/sh
export LC_ALL=C

BUILD=$( pwd )
cd /usr/bin
sudo ln -sfv python3.8 python3
cd $BUILD

python3 --version

export PATH="$BUILD"/build_libs/bin:$PATH
export BOOST_BUILD_PATH="$BUILD"/boost/boost_1_82_0/tools/build
export BOOST_ROOT="$BUILD"/boost/boost_1_82_0
export QT_SELECT=qt6

python3 -m pip install "$BUILD"/tools/ninja-1.11.1-py2.py3-none-manylinux_2_12_x86_64.manylinux2010_x86_64.whl
python3 -m pip install "$BUILD"/tools/cmake-3.26.3-py2.py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl

b2 --version
ninja --version
cmake --version

sudo update-alternatives --set gcc /usr/bin/gcc-8
sudo update-alternatives --set g++ /usr/bin/g++-8
sudo update-alternatives --set cpp /usr/bin/cpp-8

scripts/debian-update-versions
dpkg-buildpackage -uc -us -b -j4

sudo update-alternatives --auto gcc
sudo update-alternatives --auto g++
sudo update-alternatives --auto cpp

python3 -m pip uninstall -y ninja
python3 -m pip uninstall -y cmake

cd /usr/bin
sudo ln -sfv python3.6 python3
