#!/bin/sh

BUILD="$(pwd)"

cd "$BUILD"/libtorrent
cmake -B build -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=17 -Dstatic_runtime=on -DBUILD_SHARED_LIBS=off -DCMAKE_INSTALL_PREFIX="$BUILD/build_libs"
