#!/bin/sh

BUILD="$(pwd)"

echo ""
echo "Cleaning libtorrent directory"
echo ""

cd "$BUILD"/libtorrent
git clean -fdx
git submodule foreach --recursive git clean -xfd
git reset --hard
git submodule foreach --recursive git reset --hard
