#!/bin/sh

if [ ! -d libtorrent ]; then
	git clone --recurse-submodules https://github.com/arvidn/libtorrent
fi

echo ""
echo "Updating libtorrent"
echo ""

cd libtorrent
#git checkout master
#git checkout RC_2_0
git fetch
git submodule update --init --recursive --rebase
git rebase
git log --pretty="%C(yellow)%h %C(green)(%cr) %C(red)(%ar) %C(white)%s %C(blue)(%an)" -10 origin/master
