#!/bin/sh

if [ ! -d libtorrent ]; then
	git clone --recurse-submodules https://github.com/arvidn/libtorrent
fi

echo ""
echo "Updating libtorrent"
echo ""

cd libtorrent
#git checkout master
#git checkout RC_2_0
git fetch
git submodule update --init --recursive --rebase
git rebase
