#!/bin/sh

BUILD="$(pwd)"

echo ""
echo "Cleaning openssl directory"
echo ""

cd "$BUILD"/openssl

git clean -fdx
git submodule foreach --recursive git clean -xfd
git reset --hard
git submodule foreach --recursive git reset --hard
