#!/bin/sh

if [ ! -d openssl ]; then
	git clone --branch openssl-3.0 --recurse-submodules https://github.com/openssl/openssl.git
fi

echo ""
echo "Updating openssl"
echo ""

cd openssl

git fetch
git submodule update --init --recursive --rebase
git rebase
git log --pretty="%C(yellow)%h %C(green)(%cr) %C(red)(%ar) %C(white)%s %C(blue)(%an)" -10 origin/openssl-3.0
