#!/bin/sh

BUILD="$(pwd)"

case "$PKG_CONFIG_PATH" in
  '')
    export PKG_CONFIG_PATH="$BUILD/build_libs/lib/pkgconfig"
    ;;
  *)
    export PKG_CONFIG_PATH="$BUILD/build_libs/lib/pkgconfig:$PKG_CONFIG_PATH"
    ;;
esac

cd "$BUILD"/openssl

./config --prefix=/ --openssldir=/usr/lib/ssl --libdir=lib no-shared
