#!/bin/sh

if [ ! -d openssl ]; then
	git clone --branch openssl-3.0 --recurse-submodules https://github.com/openssl/openssl.git
fi

echo ""
echo "Updating openssl"
echo ""

cd openssl

git fetch
git submodule update --init --recursive --rebase
git rebase
