#!/bin/sh

BUILD="$(pwd)"

echo ""
echo "Configuring openssl"
echo ""

case "$PKG_CONFIG_PATH" in
  '')
    export PKG_CONFIG_PATH="$BUILD/build_libs/lib/pkgconfig"
    ;;
  *)
    export PKG_CONFIG_PATH="$BUILD/build_libs/lib/pkgconfig:$PKG_CONFIG_PATH"
    ;;
esac

cd "$BUILD"/openssl

./Configure --prefix=/ --openssldir=/usr/lib/ssl --libdir=lib no-shared no-idea no-mdc2 no-rc5 no-zlib no-ssl3 no-ssl3-method enable-rfc3779 enable-cms no-capieng enable-ec_nistp_64_gcc_128
