#!/bin/sh

if [ ! -d qBittorrent ]; then
	git clone https://github.com/qbittorrent/qBittorrent
fi

echo ""
echo "Updating qBittorrent"
echo ""

cd qBittorrent
#git checkout master
git fetch
git rebase
git log --pretty="%C(yellow)%h %C(green)(%cr) %C(red)(%ar) %C(white)%s %C(blue)(%an)" -10 origin/master
