#!/bin/sh

if [ ! -d qBittorrent ]; then
	git clone https://github.com/qbittorrent/qBittorrent
fi

echo ""
echo "Updating qBittorrent"
echo ""

cd qBittorrent
#git checkout master
git fetch
git rebase
