#!/bin/sh

if [ ! -d zlib ]; then
	git clone https://github.com/madler/zlib
fi

echo ""
echo "Updating zlib"
echo ""

cd zlib

git fetch
git rebase
git log --pretty="%C(yellow)%h %C(green)(%cr) %C(red)(%ar) %C(white)%s %C(blue)(%an)" -10 origin/master
